// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: partner/organization/v1/organization.proto

package organizationv1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	organizationcategoryv1 "ten80/proto/common/enums/organizationcategoryv1"
	v1 "ten80/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetOrganizationResponse_Status int32

const (
	GetOrganizationResponse_STATUS_UNSPECIFIED        GetOrganizationResponse_Status = 0
	GetOrganizationResponse_STATUS_SUCCESS            GetOrganizationResponse_Status = 1
	GetOrganizationResponse_STATUS_ERROR              GetOrganizationResponse_Status = 2
	GetOrganizationResponse_STATUS_INVALID_PARTNER_ID GetOrganizationResponse_Status = 3
	GetOrganizationResponse_STATUS_NOT_FOUND          GetOrganizationResponse_Status = 4
)

// Enum value maps for GetOrganizationResponse_Status.
var (
	GetOrganizationResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
		3: "STATUS_INVALID_PARTNER_ID",
		4: "STATUS_NOT_FOUND",
	}
	GetOrganizationResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":        0,
		"STATUS_SUCCESS":            1,
		"STATUS_ERROR":              2,
		"STATUS_INVALID_PARTNER_ID": 3,
		"STATUS_NOT_FOUND":          4,
	}
)

func (x GetOrganizationResponse_Status) Enum() *GetOrganizationResponse_Status {
	p := new(GetOrganizationResponse_Status)
	*p = x
	return p
}

func (x GetOrganizationResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetOrganizationResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_partner_organization_v1_organization_proto_enumTypes[0].Descriptor()
}

func (GetOrganizationResponse_Status) Type() protoreflect.EnumType {
	return &file_partner_organization_v1_organization_proto_enumTypes[0]
}

func (x GetOrganizationResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetOrganizationResponse_Status.Descriptor instead.
func (GetOrganizationResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{1, 0}
}

type SearchOrganizationResponse_Status int32

const (
	SearchOrganizationResponse_STATUS_UNSPECIFIED        SearchOrganizationResponse_Status = 0
	SearchOrganizationResponse_STATUS_SUCCESS            SearchOrganizationResponse_Status = 1
	SearchOrganizationResponse_STATUS_ERROR              SearchOrganizationResponse_Status = 2
	SearchOrganizationResponse_STATUS_INVALID_PARTNER_ID SearchOrganizationResponse_Status = 3
)

// Enum value maps for SearchOrganizationResponse_Status.
var (
	SearchOrganizationResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
		3: "STATUS_INVALID_PARTNER_ID",
	}
	SearchOrganizationResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":        0,
		"STATUS_SUCCESS":            1,
		"STATUS_ERROR":              2,
		"STATUS_INVALID_PARTNER_ID": 3,
	}
)

func (x SearchOrganizationResponse_Status) Enum() *SearchOrganizationResponse_Status {
	p := new(SearchOrganizationResponse_Status)
	*p = x
	return p
}

func (x SearchOrganizationResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOrganizationResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_partner_organization_v1_organization_proto_enumTypes[1].Descriptor()
}

func (SearchOrganizationResponse_Status) Type() protoreflect.EnumType {
	return &file_partner_organization_v1_organization_proto_enumTypes[1]
}

func (x SearchOrganizationResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOrganizationResponse_Status.Descriptor instead.
func (SearchOrganizationResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{3, 0}
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationKey string `protobuf:"bytes,1,opt,name=organization_key,json=organizationKey,proto3" json:"organization_key,omitempty"`
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_organization_v1_organization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_organization_v1_organization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizationRequest) GetOrganizationKey() string {
	if x != nil {
		return x.OrganizationKey
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       GetOrganizationResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=partner.organization.v1.GetOrganizationResponse_Status" json:"status,omitempty"`
	Error        *v1.Error                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Organization *v1.Organization               `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_organization_v1_organization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_organization_v1_organization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrganizationResponse) GetStatus() GetOrganizationResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetOrganizationResponse_STATUS_UNSPECIFIED
}

func (x *GetOrganizationResponse) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetOrganizationResponse) GetOrganization() *v1.Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type SearchOrganizationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of this organization.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The category of this organization (used by FI's to as part of their processing rules).
	Category organizationcategoryv1.OrganizationCategory `protobuf:"varint,2,opt,name=category,proto3,enum=common.enums.organizationcategory.v1.OrganizationCategory" json:"category,omitempty"`
}

func (x *SearchOrganizationRequest) Reset() {
	*x = SearchOrganizationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_organization_v1_organization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrganizationRequest) ProtoMessage() {}

func (x *SearchOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_organization_v1_organization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrganizationRequest.ProtoReflect.Descriptor instead.
func (*SearchOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *SearchOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchOrganizationRequest) GetCategory() organizationcategoryv1.OrganizationCategory {
	if x != nil {
		return x.Category
	}
	return organizationcategoryv1.OrganizationCategory_ORGANIZATION_CATEGORY_UNSPECIFIED
}

type SearchOrganizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        SearchOrganizationResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=partner.organization.v1.SearchOrganizationResponse_Status" json:"status,omitempty"`
	Error         *v1.Error                         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Organizations []*v1.Organization                `protobuf:"bytes,3,rep,name=organizations,proto3" json:"organizations,omitempty"`
}

func (x *SearchOrganizationResponse) Reset() {
	*x = SearchOrganizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partner_organization_v1_organization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrganizationResponse) ProtoMessage() {}

func (x *SearchOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_organization_v1_organization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrganizationResponse.ProtoReflect.Descriptor instead.
func (*SearchOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_partner_organization_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *SearchOrganizationResponse) GetStatus() SearchOrganizationResponse_Status {
	if x != nil {
		return x.Status
	}
	return SearchOrganizationResponse_STATUS_UNSPECIFIED
}

func (x *SearchOrganizationResponse) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SearchOrganizationResponse) GetOrganizations() []*v1.Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

var File_partner_organization_v1_organization_proto protoreflect.FileDescriptor

var file_partner_organization_v1_organization_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x40, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x22, 0xcc, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e,
	0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41,
	0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x04,
	0x22, 0x87, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x56, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xbe, 0x02, 0x0a, 0x1a, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x70, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x0d, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x65, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50,
	0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x42, 0x66, 0x0a, 0x25, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x74, 0x65, 0x6e, 0x38, 0x30, 0x2e, 0x70, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x42, 0x11, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x22, 0x74, 0x65, 0x6e, 0x38, 0x30, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02, 0x05, 0x54, 0x45,
	0x4e, 0x38, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partner_organization_v1_organization_proto_rawDescOnce sync.Once
	file_partner_organization_v1_organization_proto_rawDescData = file_partner_organization_v1_organization_proto_rawDesc
)

func file_partner_organization_v1_organization_proto_rawDescGZIP() []byte {
	file_partner_organization_v1_organization_proto_rawDescOnce.Do(func() {
		file_partner_organization_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(file_partner_organization_v1_organization_proto_rawDescData)
	})
	return file_partner_organization_v1_organization_proto_rawDescData
}

var file_partner_organization_v1_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_partner_organization_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_partner_organization_v1_organization_proto_goTypes = []interface{}{
	(GetOrganizationResponse_Status)(0),              // 0: partner.organization.v1.GetOrganizationResponse.Status
	(SearchOrganizationResponse_Status)(0),           // 1: partner.organization.v1.SearchOrganizationResponse.Status
	(*GetOrganizationRequest)(nil),                   // 2: partner.organization.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),                  // 3: partner.organization.v1.GetOrganizationResponse
	(*SearchOrganizationRequest)(nil),                // 4: partner.organization.v1.SearchOrganizationRequest
	(*SearchOrganizationResponse)(nil),               // 5: partner.organization.v1.SearchOrganizationResponse
	(*v1.Error)(nil),                                 // 6: common.v1.Error
	(*v1.Organization)(nil),                          // 7: common.v1.Organization
	(organizationcategoryv1.OrganizationCategory)(0), // 8: common.enums.organizationcategory.v1.OrganizationCategory
}
var file_partner_organization_v1_organization_proto_depIdxs = []int32{
	0, // 0: partner.organization.v1.GetOrganizationResponse.status:type_name -> partner.organization.v1.GetOrganizationResponse.Status
	6, // 1: partner.organization.v1.GetOrganizationResponse.error:type_name -> common.v1.Error
	7, // 2: partner.organization.v1.GetOrganizationResponse.organization:type_name -> common.v1.Organization
	8, // 3: partner.organization.v1.SearchOrganizationRequest.category:type_name -> common.enums.organizationcategory.v1.OrganizationCategory
	1, // 4: partner.organization.v1.SearchOrganizationResponse.status:type_name -> partner.organization.v1.SearchOrganizationResponse.Status
	6, // 5: partner.organization.v1.SearchOrganizationResponse.error:type_name -> common.v1.Error
	7, // 6: partner.organization.v1.SearchOrganizationResponse.organizations:type_name -> common.v1.Organization
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_partner_organization_v1_organization_proto_init() }
func file_partner_organization_v1_organization_proto_init() {
	if File_partner_organization_v1_organization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_partner_organization_v1_organization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrganizationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_organization_v1_organization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrganizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_organization_v1_organization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchOrganizationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partner_organization_v1_organization_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchOrganizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partner_organization_v1_organization_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partner_organization_v1_organization_proto_goTypes,
		DependencyIndexes: file_partner_organization_v1_organization_proto_depIdxs,
		EnumInfos:         file_partner_organization_v1_organization_proto_enumTypes,
		MessageInfos:      file_partner_organization_v1_organization_proto_msgTypes,
	}.Build()
	File_partner_organization_v1_organization_proto = out.File
	file_partner_organization_v1_organization_proto_rawDesc = nil
	file_partner_organization_v1_organization_proto_goTypes = nil
	file_partner_organization_v1_organization_proto_depIdxs = nil
}
